language: python
python:
  - "2.7"
install:
  - pip --default-timeout=180 install -r requirements.txt
  - pip --default-timeout=180 install -r test_requirements.txt

before_script:
  - psql -c 'create database lastuser_test_app;' -U postgres

script:
  - nosetests --with-timer

notifications:
  email: false
